run("Duplicate...", "duplicate");
run("Split Channels");
selectImage("C1-HEK293 non-transduced control DAPI eGFP p53 20x-1.oib");
setAutoThreshold("Default no-reset");
//run("Threshold...");
setOption("BlackBackground", true);
run("Convert to Mask");
run("Fill Holes");
run("Close");
run("Undo");
run("Watershed");
run("Fill Holes");
run("Create Selection");
saveAs("Selection", "C:/Users/sam.siljee/OneDrive - GMRI/Pictures/Immunofluorescence/p53 validation ICC 2/non-transduced control.roi");
close();
selectImage("C2-HEK293 non-transduced control DAPI eGFP p53 20x-1.oib");
open("C:/Users/sam.siljee/OneDrive - GMRI/Pictures/Immunofluorescence/p53 validation ICC 2/non-transduced control.roi");
run("Set Measurements...", "area mean integrated limit redirect=None decimal=3");
run("Measure");
